version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "marten_banking_postgres"
    environment:
        POSTGRES_USER: banking_user
        POSTGRES_PASSWORD: not_magical_scary
        POSTGRES_DB: marten_test
    ports:
      - "5432:5432"
    volumes:
      - banking_dbdata:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
    banking_dbdata: